version: '3.8'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: